#
#
#
# List of all client sources
#
#
#

set(CLIENT_SOURCES
	../../common/compiledcaptionswap.cpp 
    ../../common/language.cpp 
    ../../common/randoverride.cpp 
    ../../game/client/c_vote_controller.cpp 
    ../../game/shared/achievementmgr.cpp 
    ../../game/shared/achievements_hlx.cpp 
    ../../game/shared/achievement_saverestore.cpp 
    ../../game/shared/activitylist.cpp 
    ../../game/shared/ammodef.cpp 
    ../../game/shared/animation.cpp 
    ../../game/shared/baseachievement.cpp 
    ../../game/shared/basecombatcharacter_shared.cpp 
    ../../game/shared/basecombatweapon_shared.cpp 
    ../../game/shared/baseentity_shared.cpp 
    ../../game/shared/basegrenade_shared.cpp 
    ../../game/shared/baseparticleentity.cpp 
    ../../game/shared/baseplayer_shared.cpp 
    ../../game/shared/baseprojectile.cpp 
    ../../game/shared/baseviewmodel_shared.cpp 
    ../../game/shared/base_playeranimstate.cpp 
    ../../game/shared/beam_shared.cpp 
    ../../game/shared/cam_thirdperson.cpp 
    ../../game/shared/collisionproperty.cpp 
    ../../game/shared/death_pose.cpp 
    ../../game/shared/debugoverlay_shared.cpp 
    ../../game/shared/decals.cpp 
    ../../game/shared/effect_dispatch_data.cpp 
    ../../game/shared/ehandle.cpp 
    ../../game/shared/entitylist_base.cpp 
    ../../game/shared/EntityParticleTrail_Shared.cpp 
    ../../game/shared/env_detail_controller.cpp 
    ../../game/shared/env_wind_shared.cpp 
    ../../game/shared/eventlist.cpp 
    ../../game/shared/func_ladder.cpp 
    ../../game/shared/gamemovement.cpp 
    ../../game/shared/gamerules.cpp 
    ../../game/shared/gamerules_register.cpp 
    ../../game/shared/GameStats.cpp 
    ../../game/shared/gamestringpool.cpp 
    ../../game/shared/gamevars_shared.cpp 
    ../../game/shared/hintmessage.cpp 
    ../../game/shared/hintsystem.cpp 
    ../../game/shared/hl2/basehlcombatweapon_shared.cpp 
    ../../game/shared/hl2/env_headcrabcanister_shared.cpp 
    ../../game/shared/hl2/hl2_gamerules.cpp 
    ../../game/shared/hl2/hl2_usermessages.cpp 
    ../../game/shared/hl2/hl_gamemovement.cpp 
    ../../game/shared/hl2mp/hl2mp_gamerules.cpp 
    ../../game/shared/hl2mp/hl2mp_player_shared.cpp 
    ../../game/shared/hl2mp/hl2mp_weapon_parse.cpp 
    ../../game/shared/hl2mp/weapon_357.cpp 
    ../../game/shared/hl2mp/weapon_ar2.cpp 
    ../../game/shared/hl2mp/weapon_crossbow.cpp 
    ../../game/shared/hl2mp/weapon_crowbar.cpp 
    ../../game/shared/hl2mp/weapon_frag.cpp 
    ../../game/shared/hl2mp/weapon_hl2mpbase.cpp 
    ../../game/shared/hl2mp/weapon_hl2mpbasebasebludgeon.cpp 
    ../../game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.cpp 
    ../../game/shared/hl2mp/weapon_hl2mpbase_machinegun.cpp 
    ../../game/shared/hl2mp/weapon_physcannon.cpp 
    ../../game/shared/hl2mp/weapon_pistol.cpp 
    ../../game/shared/hl2mp/weapon_rpg.cpp 
    ../../game/shared/hl2mp/weapon_shotgun.cpp 
    ../../game/shared/hl2mp/weapon_slam.cpp 
    ../../game/shared/hl2mp/weapon_smg1.cpp 
    ../../game/shared/hl2mp/weapon_stunstick.cpp 
    ../../game/shared/igamesystem.cpp 
    ../../game/shared/interval.cpp 
    ../../game/shared/mapentities_shared.cpp 
    ../../game/shared/movevars_shared.cpp 
    ../../game/shared/mp_shareddefs.cpp 
    ../../game/shared/multiplay_gamerules.cpp 
    ../../game/shared/obstacle_pushaway.cpp 
    ../../game/shared/particlesystemquery.cpp 
    ../../game/shared/particle_parse.cpp 
    ../../game/shared/particle_property.cpp 
    ../../game/shared/physics_main_shared.cpp 
    ../../game/shared/physics_saverestore.cpp 
    ../../game/shared/physics_shared.cpp 
    ../../game/shared/point_bonusmaps_accessor.cpp 
    ../../game/shared/point_posecontroller.cpp 
    ../../game/shared/precache_register.cpp 
    ../../game/shared/predictableid.cpp 
    ../../game/shared/predicted_viewmodel.cpp 
    ../../game/shared/predictioncopy.cpp 
    ../../game/shared/props_shared.cpp 
    ../../game/shared/ragdoll_shared.cpp 
    ../../game/shared/rope_helpers.cpp 
    ../../game/shared/saverestore.cpp 
    ../../game/shared/sceneentity_shared.cpp 
    ../../game/shared/script_intro_shared.cpp 
    ../../game/shared/sequence_Transitioner.cpp 
    ../../game/shared/sheetsimulator.cpp 
    ../../game/shared/simtimer.cpp 
    ../../game/shared/singleplay_gamerules.cpp 
    ../../game/shared/sixense/sixense_convars.cpp 
    ../../game/shared/SoundEmitterSystem.cpp 
    ../../game/shared/soundenvelope.cpp 
    ../../game/shared/Sprite.cpp 
    ../../game/shared/SpriteTrail.cpp 
    ../../game/shared/studio_shared.cpp 
    ../../game/shared/takedamageinfo.cpp 
    ../../game/shared/teamplayroundbased_gamerules.cpp 
    ../../game/shared/teamplay_gamerules.cpp 
    ../../game/shared/teamplay_round_timer.cpp 
    ../../game/shared/test_ehandle.cpp 
    ../../game/shared/usercmd.cpp 
    ../../game/shared/usermessages.cpp 
    ../../game/shared/util_shared.cpp 
    ../../game/shared/vehicle_viewblend_shared.cpp 
    ../../game/shared/voice_banmgr.cpp 
    ../../game/shared/voice_status.cpp 
    ../../game/shared/weapon_parse.cpp 
    ../../public/bone_accessor.cpp 
    ../../public/bone_setup.cpp 
    ../../public/client_class.cpp 
    ../../public/collisionutils.cpp 
    ../../public/crtmemdebug.cpp 
    ../../public/dt_recv.cpp 
    ../../public/dt_utlvector_common.cpp 
    ../../public/dt_utlvector_recv.cpp 
    ../../public/filesystem_helpers.cpp 
    ../../public/haptics/haptic_msgs.cpp 
    ../../public/interpolatortypes.cpp 
    ../../public/jigglebones.cpp 
    ../../public/networkvar.cpp 
    ../../public/posedebugger.cpp 
    ../../public/renamed_recvtable_compat.cpp 
    ../../public/rope_physics.cpp 
    ../../public/scratchpad3d.cpp 
    ../../public/ScratchPadUtils.cpp 
    ../../public/sentence.cpp 
    ../../public/simple_physics.cpp 
    ../../public/SoundParametersInternal.cpp 
    ../../public/stringregistry.cpp 
    ../../public/studio.cpp 
    ../../public/tier0/memoverride.cpp 
    ../../public/tools/bonelist.cpp 
    ../../public/vallocator.cpp 
    ../../public/vgui_controls/vgui_controls.cpp 
    achievement_notification_panel.cpp 
    alphamaterialproxy.cpp 
    animatedentitytextureproxy.cpp 
    animatedoffsettextureproxy.cpp 
    animatedtextureproxy.cpp 
    AnimateSpecificTextureProxy.cpp 
    baseanimatedtextureproxy.cpp 
    baseclientrendertargets.cpp 
    basepresence.cpp 
    beamdraw.cpp 
    bone_merge_cache.cpp 
    camomaterialproxy.cpp 
    cdll_bounded_cvars.cpp 
    cdll_client_int.cpp 
    cdll_util.cpp 
    classmap.cpp 
    clienteffectprecachesystem.cpp 
    cliententitylist.cpp 
    clientleafsystem.cpp 
    clientmode_shared.cpp 
    clientshadowmgr.cpp 
    clientsideeffects.cpp 
    clientsideeffects_test.cpp 
    clientsteamcontext.cpp 
    client_factorylist.cpp 
    client_thinklist.cpp 
    client_virtualreality.cpp 
    cl_mat_stub.cpp 
    colorcorrectionmgr.cpp 
    commentary_modelviewer.cpp 
    c_ai_basehumanoid.cpp 
    c_ai_basenpc.cpp 
    c_baseanimating.cpp 
    c_baseanimatingoverlay.cpp 
    c_basecombatcharacter.cpp 
    c_basecombatweapon.cpp 
    c_basedoor.cpp 
    c_baseentity.cpp 
    c_baseflex.cpp 
    c_baseplayer.cpp 
    c_basetempentity.cpp 
    c_baseviewmodel.cpp 
    c_breakableprop.cpp 
    c_colorcorrection.cpp 
    c_colorcorrectionvolume.cpp 
    c_dynamiclight.cpp 
    c_effects.cpp 
    c_entitydissolve.cpp 
    c_entityparticletrail.cpp 
    c_env_fog_controller.cpp 
    c_env_particlescript.cpp 
    c_env_projectedtexture.cpp 
    c_env_screenoverlay.cpp 
    c_env_tonemap_controller.cpp 
    c_fire_smoke.cpp 
    c_fish.cpp 
    c_func_areaportalwindow.cpp 
    c_func_breakablesurf.cpp 
    c_func_conveyor.cpp 
    c_func_dust.cpp 
    c_func_lod.cpp 
    c_func_occluder.cpp 
    c_func_reflective_glass.cpp 
    c_func_rotating.cpp 
    c_func_smokevolume.cpp 
    c_func_tracktrain.cpp 
    c_gib.cpp 
    c_hairball.cpp 
    c_impact_effects.cpp 
    c_info_overlay_accessor.cpp 
    c_lightglow.cpp 
    C_MaterialModifyControl.cpp 
    c_movie_explosion.cpp 
    c_particle_fire.cpp 
    c_particle_smokegrenade.cpp 
    c_particle_system.cpp 
    c_physbox.cpp 
    c_physicsprop.cpp 
    c_physmagnet.cpp 
    c_pixel_visibility.cpp 
    c_plasma.cpp 
    c_playerresource.cpp 
    c_point_camera.cpp 
    c_point_commentary_node.cpp 
    c_props.cpp 
    c_prop_vehicle.cpp 
    c_ragdoll_manager.cpp 
    c_recipientfilter.cpp 
    c_rope.cpp 
    c_rumble.cpp 
    c_sceneentity.cpp 
    c_shadowcontrol.cpp 
    c_slideshow_display.cpp 
    c_smokestack.cpp 
    c_smoke_trail.cpp 
    c_soundscape.cpp 
    c_spotlight_end.cpp 
    c_sprite.cpp 
    c_sprite_perfmonitor.cpp 
    c_steamjet.cpp 
    c_stickybolt.cpp 
    c_sun.cpp 
    c_te.cpp 
    c_team.cpp 
    c_team_objectiveresource.cpp 
    c_team_train_watcher.cpp 
    c_tesla.cpp 
    c_testtraceline.cpp 
    c_test_proxytoggle.cpp 
    c_te_armorricochet.cpp 
    c_te_basebeam.cpp 
    c_te_beamentpoint.cpp 
    c_te_beaments.cpp 
    c_te_beamfollow.cpp 
    c_te_beamlaser.cpp 
    c_te_beampoints.cpp 
    c_te_beamring.cpp 
    c_te_beamringpoint.cpp 
    c_te_beamspline.cpp 
    c_te_bloodsprite.cpp 
    c_te_bloodstream.cpp 
    c_te_breakmodel.cpp 
    c_te_bspdecal.cpp 
    c_te_bubbles.cpp 
    c_te_bubbletrail.cpp 
    c_te_clientprojectile.cpp 
    c_te_decal.cpp 
    c_te_dynamiclight.cpp 
    c_te_effect_dispatch.cpp 
    c_te_energysplash.cpp 
    c_te_explosion.cpp 
    c_te_fizz.cpp 
    c_te_footprint.cpp 
    c_te_glassshatter.cpp 
    c_te_glowsprite.cpp 
    c_te_impact.cpp 
    c_te_killplayerattachments.cpp 
    c_te_largefunnel.cpp 
    c_te_legacytempents.cpp 
    c_te_muzzleflash.cpp 
    c_te_particlesystem.cpp 
    c_te_physicsprop.cpp 
    c_te_playerdecal.cpp 
    c_te_projecteddecal.cpp 
    c_te_showline.cpp 
    c_te_smoke.cpp 
    c_te_sparks.cpp 
    c_te_sprite.cpp 
    c_te_spritespray.cpp 
    c_te_worlddecal.cpp 
    c_tracer.cpp 
    c_user_message_register.cpp 
    c_vehicle_choreo_generic.cpp 
    c_vehicle_jeep.cpp 
    c_vguiscreen.cpp 
    C_WaterLODControl.cpp 
    c_world.cpp 
    detailobjectsystem.cpp 
    dummyproxy.cpp 
    EffectsClient.cpp 
    entityoriginmaterialproxy.cpp 
    entity_client_tools.cpp 
    episodic/c_vort_charge_token.cpp 
    flashlighteffect.cpp 
    functionproxy.cpp 
    fx.cpp 
    fx_blood.cpp 
    fx_cube.cpp 
    fx_discreetline.cpp 
    fx_envelope.cpp 
    fx_explosion.cpp 
    fx_fleck.cpp 
    fx_impact.cpp 
    fx_interpvalue.cpp 
    fx_line.cpp 
    fx_quad.cpp 
    fx_shelleject.cpp 
    fx_sparks.cpp 
    fx_staticline.cpp 
    fx_tracer.cpp 
    fx_trail.cpp 
    fx_water.cpp 
    gametrace_client.cpp 
    game_controls/basemodelpanel.cpp 
    game_controls/basemodel_panel.cpp 
    game_controls/baseviewport.cpp 
    game_controls/ClientScoreBoardDialog.cpp 
    game_controls/commandmenu.cpp 
    game_controls/IconPanel.cpp 
    game_controls/intromenu.cpp 
    game_controls/MapOverview.cpp 
    game_controls/NavProgress.cpp 
    game_controls/SpectatorGUI.cpp 
    game_controls/teammenu.cpp 
    game_controls/vguitextwindow.cpp 
    geiger.cpp 
    glow_outline_effect.cpp 
    glow_overlay.cpp 
    history_resource.cpp 
    hl2/c_antlion_dust.cpp 
    hl2/c_ar2_explosion.cpp 
    hl2/c_barnacle.cpp 
    hl2/c_barney.cpp 
    hl2/c_basehelicopter.cpp 
    hl2/c_basehlcombatweapon.cpp 
    hl2/c_basehlplayer.cpp 
    hl2/c_citadel_effects.cpp 
    hl2/c_corpse.cpp 
    hl2/c_env_alyxtemp.cpp 
    hl2/c_env_headcrabcanister.cpp 
    hl2/c_env_starfield.cpp 
    hl2/C_Func_Monitor.cpp 
    hl2/c_func_tankmortar.cpp 
    hl2/c_hl2_playerlocaldata.cpp 
    hl2/c_info_teleporter_countdown.cpp 
    hl2/c_npc_antlionguard.cpp 
    hl2/c_npc_combinegunship.cpp 
    hl2/c_npc_manhack.cpp 
    hl2/c_npc_rollermine.cpp 
    hl2/c_plasma_beam_node.cpp 
    hl2/c_prop_combine_ball.cpp 
    hl2/c_rotorwash.cpp 
    hl2/c_script_intro.cpp 
    hl2/c_strider.cpp 
    hl2/c_te_concussiveexplosion.cpp 
    hl2/c_te_flare.cpp 
    hl2/c_thumper_dust.cpp 
    hl2/c_vehicle_airboat.cpp 
    hl2/c_vehicle_cannon.cpp 
    hl2/c_vehicle_crane.cpp 
    hl2/c_vehicle_prisoner_pod.cpp 
    hl2/c_waterbullet.cpp 
    hl2/c_weapon_crossbow.cpp 
    hl2/c_weapon__stubs_hl2.cpp 
    hl2/fx_antlion.cpp 
    hl2/fx_bugbait.cpp 
    hl2/fx_hl2_impacts.cpp 
    hl2/fx_hl2_tracers.cpp 
    hl2/hl2_clientmode.cpp 
    hl2/hl_in_main.cpp 
    hl2/hl_prediction.cpp 
    hl2/hud_ammo.cpp 
    hl2/hud_autoaim.cpp 
    hl2/hud_battery.cpp 
    hl2/hud_blood.cpp 
    hl2/hud_credits.cpp 
    hl2/hud_damageindicator.cpp 
    hl2/hud_filmdemo.cpp 
    hl2/hud_flashlight.cpp 
    hl2/hud_hdrdemo.cpp 
    hl2/hud_health.cpp 
    hl2/hud_poisondamageindicator.cpp 
    hl2/hud_quickinfo.cpp 
    hl2/hud_suitpower.cpp 
    hl2/hud_weaponselection.cpp 
    hl2/hud_zoom.cpp 
    hl2/shieldproxy.cpp 
    hl2/vgui_rootpanel_hl2.cpp 
    hl2mp/clientmode_hl2mpnormal.cpp 
    hl2mp/c_hl2mp_player.cpp 
    hl2mp/c_te_hl2mp_shotgun_shot.cpp 
    hl2mp/hl2mp_hud_chat.cpp 
    hl2mp/hl2mp_hud_target_id.cpp 
    hl2mp/hl2mp_hud_team.cpp 
    hl2mp/hud_deathnotice.cpp 
    hl2mp/ui/backgroundpanel.cpp 
    hl2mp/ui/hl2mpclientscoreboard.cpp 
    hl2mp/ui/hl2mptextwindow.cpp 
    hltvcamera.cpp 
    hud.cpp 
    hud_animationinfo.cpp 
    hud_basechat.cpp 
    hud_basetimer.cpp 
    hud_bitmapnumericdisplay.cpp 
    hud_closecaption.cpp 
    hud_crosshair.cpp 
    hud_element_helper.cpp 
    hud_hintdisplay.cpp 
    hud_lcd.cpp 
    hud_msg.cpp 
    hud_numericdisplay.cpp 
    hud_pdump.cpp 
    hud_redraw.cpp 
    hud_squadstatus.cpp 
    hud_vehicle.cpp 
    hud_voicestatus.cpp 
    hud_weapon.cpp 
    initializer.cpp 
    interpolatedvar.cpp 
    in_camera.cpp 
    in_joystick.cpp 
    in_main.cpp 
    in_mouse.cpp 
    IsNPCProxy.cpp 
    lampbeamproxy.cpp 
    lamphaloproxy.cpp 
    mathproxy.cpp 
    matrixproxy.cpp 
    menu.cpp 
    message.cpp 
    movehelper_client.cpp 
    mp3player.cpp 
    mumble.cpp 
    panelmetaclassmgr.cpp 
    particlemgr.cpp 
    particlesphererenderer.cpp 
    particles_attractor.cpp 
    particles_ez.cpp 
    particles_localspace.cpp 
    particles_new.cpp 
    particles_simple.cpp 
    particle_collision.cpp 
    particle_litsmokeemitter.cpp 
    particle_proxies.cpp 
    particle_simple3d.cpp 
    perfvisualbenchmark.cpp 
    physics.cpp 
    physics_main_client.cpp 
    physpropclientside.cpp 
    playerandobjectenumerator.cpp 
    playerspawncache.cpp 
    prediction.cpp 
    proxyentity.cpp 
    ProxyHealth.cpp 
    proxyplayer.cpp 
    proxypupil.cpp 
    ragdoll.cpp 
    recvproxy.cpp 
    rendertexture.cpp 
    replay/cdll_replay.cpp 
    replay/replaycamera.cpp 
    ScreenSpaceEffects.cpp 
    simple_keys.cpp 
    sixense/in_sixense.cpp 
    sixense/in_sixense_gesture_bindings.cpp 
    smoke_fog_overlay.cpp 
    splinepatch.cpp 
    spritemodel.cpp 
    stdafx.cpp 
    studio_stats.cpp 
    texturescrollmaterialproxy.cpp 
    text_message.cpp 
    timematerialproxy.cpp 
    toggletextureproxy.cpp 
    toolframework_client.cpp 
    train.cpp 
    vgui_avatarimage.cpp 
    vgui_basepanel.cpp 
    vgui_bitmapbutton.cpp 
    vgui_bitmapimage.cpp 
    vgui_bitmappanel.cpp 
    vgui_centerstringpanel.cpp 
    vgui_consolepanel.cpp 
    vgui_debugoverlaypanel.cpp 
    vgui_fpspanel.cpp 
    vgui_game_viewport.cpp 
    vgui_grid.cpp 
    vgui_int.cpp 
    vgui_loadingdiscpanel.cpp 
    vgui_messagechars.cpp 
    vgui_netgraphpanel.cpp 
    vgui_schemevisualizer.cpp 
    vgui_slideshow_display_screen.cpp 
    vgui_video.cpp 
    vgui_video_player.cpp 
    view.cpp 
    viewangleanim.cpp 
    ViewConeImage.cpp 
    viewdebug.cpp 
    viewpostprocess.cpp 
    viewrender.cpp 
    view_beams.cpp 
    view_effects.cpp 
    view_scene.cpp 
    warp_overlay.cpp 
    WaterLODMaterialProxy.cpp 
    weapons_resource.cpp 
    weapon_selection.cpp 
    WorldDimsProxy.cpp 			
)

