#
#
# Directory listings
#
#

set(SOURCE_PUBLIC_INCLUDE_DIR 		"${CMAKE_HOME_DIRECTORY}/public/")
set(SOURCE_TIER0_INCLUDE_DIR		"${CMAKE_HOME_DIRECTORY}/public/tier0")
set(SOURCE_TIER1_INCLUDE_DIR		"${CMAKE_HOME_DIRECTORY}/public/tier1")
set(SOURCE_COMMON_INCLUDE_DIR		"${CMAKE_HOME_DIRECTORY}/common/")
set(SOURCE_UTILS_COMMON_INCLUDE_DIR	"${CMAKE_HOME_DIRECTORY}/utils/common/")
set(SOURCE_MATHLIB_INCLUDE_DIR		"${CMAKE_HOME_DIRECTORY}/public/mathlib")


#set(SOURCE_CLIENT_SRC_DIR			"${CMAKE_HOME_DIRECTORY}/game/client")


set(LINUX32_LIB_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/linux32")
set(LINUX64_LIB_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/linux64")
set(WIN32_LIB_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/win32")
set(WIN64_LIB_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/win64")

set(LINUX32_DLL_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/bin/linux32")
set(LINUX64_DLL_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/bin/linux64")
set(WIN32_DLL_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/bin/win32")
set(WIN64_DLL_OUTPUT_DIR		"${CMAKE_HOME_DIRECTORY}/bin/win64")

set(LINUX32_INTERMEDIATE_DIR	"${CMAKE_HOME_DIRECTORY}/intermediate/linux32")
set(LINUX64_INTERMEDIATE_DIR	"${CMAKE_HOME_DIRECTORY}/intermediate/linux64")
set(WIN32_INTERMEDIATE_DIR		"${CMAKE_HOME_DIRECTORY}/intermediate/win32")
set(WIN64_INTERMEDIATE_DIR		"${CMAKE_HOME_DIRECTORY}/intermediate/win64")

set(LINUX32_PUBLIC_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/linux32")
set(LINUX64_PUBLIC_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/linux64")
set(WIN32_PUBLIC_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/win32")
set(WIN64_PUBLIC_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/public/win64")

set(LINUX32_COMMON_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/common/linux32")
set(LINUX64_COMMON_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/common/linux64")
set(WIN32_COMMON_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/common/win32")
set(WIN64_COMMON_LIB_DIR		"${CMAKE_HOME_DIRECTORY}/lib/common/win64")

set(SOURCE_TIER1_SRC_DIR		"${CMAKE_HOME_DIRECTORY}/tier1")
set(SOURCE_DIRECTORY			"${CMAKE_HOME_DIRECTORY}")
set(GAME_DIRECTORY				"${CMAKE_HOME_DIRECTORY}/game/")
set(SHARED_DIRECTORY			"${CMAKE_HOME_DIRECTORY}/game/shared")
set(SERVER_DIRECTORY			"${CMAKE_HOME_DIRECTORY}/game/server")
set(CLIENT_DIRECTORY			"${CMAKE_HOME_DIRECTORY}/game/client")

if(DEFINED LINUX64 OR DEFINED LINUX32)
	set(VULKAN_INCLUDE_DIRECTORY	"${CMAKE_HOME_DIRECTORY}/thirdparty/Vulkan/linux64/include/")
	set(VULKAN_LIB_DIRECTORY		"${CMAKE_HOME_DIRECTORY}/thirdpary/Vulkan/linux64/lib")
endif(DEFINED LINUX64 OR DEFINED LINUX64)

if(DEFINED LINUX32)
	set(PLATFORM_COMMON_LIB_DIR				"${LINUX32_COMMON_LIB_DIR}")
	set(PLATFORM_PUBLIC_LIB_DIR	"${LINUX32_PUBLIC_LIB_DIR}")
elseif(DEFINED LINUX64)
	set(PLATFORM_COMMON_LIB_DIR	"${LINUX64_COMMON_LIB_DIR}")
	set(PLATFORM_PUBLIC_LIB_DIR	"${LINUX64_PUBLIC_LIB_DIR}")
elseif(DEFINED WIN32)
	set(PLATFORM_COMMON_LIB_DIR	"${WIN32_COMMON_LIB_DIR}")
	set(PLATFORM_PUBLIC_LIB_DIR	"${WIN32_PUBLIC_LIB_DIR}")
elseif(DEFINED WIN64)
	set(PLATFORM_COMMON_LIB_DIR	"${WIN64_COMMON_LIB_DIR}")
	set(PLATFORM_PUBLIC_LIB_DIR	"${WIN64_PUBLIC_LIB_DIR}")
endif(DEFINED LINUX32)
